- hosts: all
  gather_facts: False
  tasks:
    - script: setup-ic.sh
      name: setup-ic.sh
    - shell: sudo chmod a+rwx,o+t /var/www/fileserver
      name: chmod /var/www/fileserver
    - script: download-srv.sh 2>&1 | tee /tmp/work/download.log
      name: download.sh
